### ISSUE TITLE
Está funcionando?

### ISSUE THREAD

**Issue by edpichler** [fabito/busca-cep-java-client#6]
@fabito boa noite, como está a API? 
- Funcionando bem? 
- Alguma empresa usando em produção?
- O componente visita a página HTML dos correios?

**Comment by fabito** [comment]
@edpichler ,

Funciona sim. O único problema é que é bem acoplado ao markup da página de busca de CEP, ou seja, caso resolvam mudar, quebra a lib.
Fora isso funcion bem!

valeu

**Comment by edpichler** [comment]
E isso tem acontecido com frequencia? Sera q da pra usar em sistemas
empresariais?

**Comment by edpichler** [comment]
@fabito viu minha úlitma pergunta?

**Comment by fabito** [comment]
@edpichler, 

Aconteceu uma única vez desde que criei a lib.
Acho que dá pra usar sim. 
Mas tiraria do caminho crítico - deixaria como uma ferramenta de apoio.
Outra ideia é publicar como um microserviço e fazer todas as applicações apontar para ele, daí caso precise dar manutenção arrumaria num lugar só.

valeu

**Comment by edpichler** [comment]
@fabito meu medo é o correios começar pedir captcha.

Valeu pelas info.

**Comment by fabito** [comment]
Pode acontecer. 
Daí vou ter de aposentar a lib. :-1: 
Demorou pra ter um API oficial, não ?

**Comment by edpichler** [comment]
@fabito Mafia.
Se pedirem captcha a solução é comprar a base deles com atualização mensal, não tem jeito.
